# mongodb-deployment.yaml
# Ce fichier définit un StatefulSet pour déployer MongoDB avec stockage persistant.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  # Nombre de réplicas pour MongoDB
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
            - name: mongodb-config-volume
              mountPath: /etc/mongo-config
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-storage
        - name: mongodb-config-volume
          configMap:
            name: mongodb-config
